"use client";

import { useState } from "react";
import { toast } from "sonner";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import type { GuideBlock, Property } from "@/types";

interface ImportResult {
  title: string | null;
  description: string | null;
  address: string | null;
  max_guests: number | null;
  bedrooms: number | null;
  bathrooms: number | null;
  checkin_time: string | null;
  checkout_time: string | null;
  house_rules: string[];
}

type FieldKey =
  | "title"
  | "description"
  | "address"
  | "max_guests"
  | "bedrooms"
  | "bathrooms"
  | "checkin_time"
  | "checkout_time"
  | "house_rules";

const FIELD_LABELS: Record<FieldKey, string> = {
  title: "Nombre del alojamiento",
  description: "Descripción",
  address: "Dirección",
  max_guests: "Huéspedes máximos",
  bedrooms: "Habitaciones",
  bathrooms: "Baños",
  checkin_time: "Hora de check-in",
  checkout_time: "Hora de check-out",
  house_rules: "Normas de la casa",
};

// Airbnb sometimes serves a computed summary ("Rental unit in Seville · ★5.0
// · 3 bedrooms · 3 beds · 1 private bath") as the page's og:title instead of
// the host's actual listing name — that string is technically "found" but
// isn't safe to apply as the property name/address without a human check.
// Fields matching this are left unchecked by default instead of preselected.
function looksAutoGenerated(value: string): boolean {
  return /★|\d+\s*(bedrooms?|beds?|baths?|habitaciones?|dormitorios?|ba[ñn]os?)/i.test(value);
}

async function findOrCreateBlock(
  propertyId: string,
  type: "checkin" | "checkout" | "rules",
  blocks: GuideBlock[],
  onBlockCreated: (block: GuideBlock) => void
): Promise<GuideBlock | null> {
  const existing = blocks.find((b) => b.type === type);
  if (existing) return existing;

  const response = await fetch(`/api/properties/${propertyId}/blocks`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ type }),
  });
  if (!response.ok) return null;
  const { block } = await response.json();
  onBlockCreated(block);
  return block;
}

async function patchBlockContent(id: string, content: Record<string, unknown>) {
  return fetch(`/api/guide-blocks/${id}`, {
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ content }),
  });
}

export function AirbnbImportPanel({
  property,
  blocks,
  onBlockCreated,
  onBlockSynced,
}: {
  property: Property;
  blocks: GuideBlock[];
  onBlockCreated: (block: GuideBlock) => void;
  onBlockSynced: (id: string, patch: Partial<GuideBlock>) => void;
}) {
  const [airbnbUrl, setAirbnbUrl] = useState(property.airbnb_url ?? "");
  const [importing, setImporting] = useState(false);
  const [applying, setApplying] = useState(false);
  const [result, setResult] = useState<ImportResult | null>(null);
  const [selected, setSelected] = useState<Set<FieldKey>>(new Set());

  async function handleImport() {
    if (!airbnbUrl) return;
    setImporting(true);
    setResult(null);
    try {
      const response = await fetch("/api/properties/import-airbnb", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ url: airbnbUrl }),
      });

      const data = await response.json().catch(() => ({}));

      if (!response.ok) {
        toast.error(data.error ?? "No se pudo importar el anuncio. Rellena los datos manualmente.");
        return;
      }

      const imported = data as ImportResult;
      setResult(imported);
      const found = new Set<FieldKey>();
      let hadSuspicious = false;
      (Object.keys(FIELD_LABELS) as FieldKey[]).forEach((key) => {
        const value = imported[key];
        const hasValue = Array.isArray(value) ? value.length > 0 : value !== null && value !== "";
        if (!hasValue) return;
        if ((key === "title" || key === "address") && typeof value === "string" && looksAutoGenerated(value)) {
          hadSuspicious = true;
          return;
        }
        found.add(key);
      });
      setSelected(found);
      toast.success(
        hadSuspicious
          ? "Datos importados — revisa el nombre/dirección, no se han preseleccionado porque parecen texto genérico de Airbnb."
          : "Datos importados — revísalos y confirma qué aplicar."
      );
    } catch {
      toast.error("Error de red al importar. Rellena los datos manualmente.");
    } finally {
      setImporting(false);
    }
  }

  function toggle(key: FieldKey) {
    setSelected((prev) => {
      const next = new Set(prev);
      if (next.has(key)) next.delete(key);
      else next.add(key);
      return next;
    });
  }

  async function handleConfirm() {
    if (!result) return;
    setApplying(true);
    try {
      const propertyPatch: Record<string, unknown> = { airbnb_url: airbnbUrl };
      if (selected.has("title") && result.title) propertyPatch.name = result.title;
      if (selected.has("address") && result.address) propertyPatch.address = result.address;
      if (selected.has("description") && result.description) {
        propertyPatch.welcome_message = result.description.slice(0, 500);
      }
      if (selected.has("max_guests") && result.max_guests !== null) {
        propertyPatch.max_guests = result.max_guests;
      }
      if (selected.has("bedrooms") && result.bedrooms !== null) {
        propertyPatch.bedrooms = result.bedrooms;
      }
      if (selected.has("bathrooms") && result.bathrooms !== null) {
        propertyPatch.bathrooms = result.bathrooms;
      }

      const propertyResponse = await fetch(`/api/properties/${property.id}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(propertyPatch),
      });
      if (!propertyResponse.ok) {
        toast.error("No se pudieron guardar los datos básicos");
      }

      if (selected.has("checkin_time") && result.checkin_time) {
        const block = await findOrCreateBlock(property.id, "checkin", blocks, onBlockCreated);
        if (block) {
          const content = { ...(block.content as { time?: string; instructions?: string }), time: result.checkin_time };
          const ok = await patchBlockContent(block.id, content);
          if (ok.ok) onBlockSynced(block.id, { content });
        }
      }

      if (selected.has("checkout_time") && result.checkout_time) {
        const block = await findOrCreateBlock(property.id, "checkout", blocks, onBlockCreated);
        if (block) {
          const content = { ...(block.content as { time?: string; instructions?: string }), time: result.checkout_time };
          const ok = await patchBlockContent(block.id, content);
          if (ok.ok) onBlockSynced(block.id, { content });
        }
      }

      if (selected.has("house_rules") && result.house_rules.length > 0) {
        const block = await findOrCreateBlock(property.id, "rules", blocks, onBlockCreated);
        if (block) {
          const existingRules = (block.content as { rules?: string[] }).rules ?? [];
          const merged = Array.from(new Set([...existingRules, ...result.house_rules]));
          const content = { rules: merged };
          const ok = await patchBlockContent(block.id, content);
          if (ok.ok) onBlockSynced(block.id, { content });
        }
      }

      toast.success("Datos aplicados");
      setResult(null);
    } catch {
      toast.error("Error de red al guardar los datos importados");
    } finally {
      setApplying(false);
    }
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle className="text-sm">Importar desde Airbnb</CardTitle>
      </CardHeader>
      <CardContent className="space-y-3">
        <div className="space-y-2">
          <Label htmlFor="airbnb_url">URL de tu anuncio de Airbnb</Label>
          <div className="flex gap-2">
            <Input
              id="airbnb_url"
              value={airbnbUrl}
              onChange={(e) => setAirbnbUrl(e.target.value)}
              placeholder="https://www.airbnb.com/rooms/12345678"
            />
            <Button
              type="button"
              variant="outline"
              onClick={handleImport}
              disabled={importing || !airbnbUrl}
            >
              {importing ? "Importando..." : "Importar datos"}
            </Button>
          </div>
          <p className="text-xs text-muted-foreground">
            Best-effort: si Airbnb bloquea el acceso o no encontramos algún dato, podrás
            rellenarlo manualmente en los bloques de abajo.
          </p>
        </div>

        {result && (
          <div className="space-y-2 rounded-lg border border-border p-3">
            <p className="text-xs font-medium text-muted-foreground">
              Datos extraídos — desmarca lo que no quieras aplicar
            </p>
            {(Object.keys(FIELD_LABELS) as FieldKey[]).map((key) => {
              const value = result[key];
              const hasValue = Array.isArray(value) ? value.length > 0 : value !== null && value !== "";
              if (!hasValue) return null;
              const preview = Array.isArray(value) ? value.join(", ") : String(value);
              const suspicious =
                (key === "title" || key === "address") &&
                typeof value === "string" &&
                looksAutoGenerated(value);
              return (
                <label key={key} className="flex items-start justify-between gap-3 text-sm">
                  <span className="min-w-0">
                    <span className="block font-medium">
                      {FIELD_LABELS[key]}
                      {suspicious && (
                        <span className="ml-1.5 text-xs font-normal text-amber-600">
                          ⚠ parece texto genérico de Airbnb, revisa antes de aplicar
                        </span>
                      )}
                    </span>
                    <span className="block truncate text-xs text-muted-foreground">{preview}</span>
                  </span>
                  <Switch checked={selected.has(key)} onCheckedChange={() => toggle(key)} />
                </label>
              );
            })}
            <div className="flex justify-end gap-2 pt-1">
              <Button type="button" variant="ghost" size="sm" onClick={() => setResult(null)}>
                Descartar
              </Button>
              <Button
                type="button"
                size="sm"
                onClick={handleConfirm}
                disabled={applying || selected.size === 0}
              >
                {applying ? "Guardando..." : "Confirmar y guardar"}
              </Button>
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
